package de.atns.shop.tray;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import de.atns.shop.tray.data.ShopConfiguration;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

@Singleton public class AuthenticateDialog extends JDialog {
// ------------------------------ FIELDS ------------------------------

    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JTextField login;
    private JPasswordField passwort;
    private JTextField shopName;
    @Inject private final AuthtokenCache authentication;
    private ShopConfiguration currentConfiguration;

// --------------------------- CONSTRUCTORS ---------------------------

    @Inject public AuthenticateDialog(final AuthtokenCache authentication) {
        this.authentication = authentication;

        setTitle("Anmeldung:");
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent e) {
                onOK();
            }
        });

        buttonCancel.addActionListener(new ActionListener() {
            public void actionPerformed(final ActionEvent e) {
                onCancel();
            }
        });

// call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(final WindowEvent e) {
                onCancel();
            }
        });

// call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(final ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        pack();
        Util.center(AuthenticateDialog.this);
    }

    private void onOK() {
        try {
            authentication.authenticate(currentConfiguration, login.getText(), new String(passwort.getPassword()));
            dispose();
        } catch (RemoteAuthenticationException e) {
            showError("Benutzername / Passwort konnte nicht geprüft werden!");
        } catch (RemoteException e) {
            System.err.println(e.getResponse());
            e.printStackTrace();
            showError("Fehler:\n" + e.getResponse());
        }
        currentConfiguration = null;
    }

    private void showError(final String msg) {
        JOptionPane.showMessageDialog(this, msg, "Fehler", JOptionPane.ERROR_MESSAGE);
        setVisible(false);
    }

    private void onCancel() {
        dispose();
        currentConfiguration = null;
    }

    // -------------------------- OTHER METHODS --------------------------

    public void authenticate(final String shopId) {
        shopName.setText("");
        login.setText("");
        passwort.setText("");
        login.requestFocusInWindow();
        
        currentConfiguration = new ShopConfiguration(shopId);

        final String name = currentConfiguration.getName();
        if (name == null || name.length() == 0) {
            showError("Shop mit Kennung '" + shopId + "' nicht konfiguriert!!");
            return;
        }

        shopName.setText(name);

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow"));
        CellConstraints cc = new CellConstraints();
        contentPane.add(panel1, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 0, 0, 5)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow"));
        panel1.add(panel2, cc.xy(3, 1));
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel2.add(buttonOK, cc.xy(1, 1));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panel2.add(buttonCancel, cc.xy(3, 1));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:150px:noGrow,left:4dlu:noGrow,fill:150px:grow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:grow"));
        contentPane.add(panel3, cc.xy(1, 1));
        final JLabel label1 = new JLabel();
        label1.setText("Benutzer:");
        panel3.add(label1, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.TOP, new Insets(6, 5, 0, 0)));
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        panel3.add(label2, new CellConstraints(1, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.TOP, new Insets(6, 5, 0, 0)));
        login = new JTextField();
        panel3.add(login, new CellConstraints(3, 3, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 0, 0, 5)));
        passwort = new JPasswordField();
        panel3.add(passwort, new CellConstraints(3, 5, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 0, 0, 5)));
        final JLabel label3 = new JLabel();
        label3.setEnabled(true);
        label3.setText("Shop");
        panel3.add(label3, new CellConstraints(1, 1, 1, 1, CellConstraints.DEFAULT, CellConstraints.TOP, new Insets(6, 5, 0, 0)));
        shopName = new JTextField();
        shopName.setEditable(false);
        shopName.setEnabled(true);
        shopName.setText("<shop-name>");
        panel3.add(shopName, new CellConstraints(3, 1, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 0, 0, 5)));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
